arnold/urls.py
from django.contrib import admin
from django.urls import path, include
from bible import urls as bible_urls
from .views import homepage, aboutpage, youtubepage
from eoq import urls as eoq_urls
# from management import urls as management_urls
from lessons import urls as lessons_urls
from management import urls as management_urls
from fitness import urls as fitness_urls

urlpatterns = [
	path(r'', homepage, name='home_page'),
    path(r'admin/', admin.site.urls),
    path(r'about/', aboutpage, name='about_page'),
    path(r'bible/', include(bible_urls)),
    path(r'eoq/', include(eoq_urls)),
    path(r'youtube/', youtubepage, name='youtube_page'),
    # path(r'management/', management, include(management_urls)),
    path(r'lessons/', include(lessons_urls)),
    path(r'chart/', include(management_urls)),
    path(r'fitness/', include(fitness_urls)),
]

bible/urls.py
from django.conf.urls import url

from .views import EmotionList, EmotionCreate, VerseCreate, VerseDetail, VerseList, VerseUpdate, VerseDelete

urlpatterns = [
	url(r'^$',
		EmotionList.as_view(),
		name='emotion_list'),
	url(r'^create/$',
		EmotionCreate.as_view(),
		name='emotion_create'),
	url(r'^verse/create$',
		VerseCreate.as_view(),
		name='verse_create'),
	url(r'^verse/(?P<slug>[\w\-]+)/$',
		VerseDetail.as_view(),
		name='verse_detail'),
 	url(r'^(?P<emotion>[\w\-]+)/$',
 		VerseList.as_view(),
 		name='verse_list'),
 	url(r'^verse/(?P<slug>[\w\-]+)/update/$',
 		VerseUpdate.as_view(),
 		name='verse_update'),
 	url(r'^verse/(?P<slug>[\w\-]+)/delete/$',
 		VerseDelete.as_view(),
 		name='verse_delete'),
]

eoq/urls.py
from django.conf.urls import url
from .views import upload_file

urlpatterns = [
	url(r'^$',
		upload_file,
		name='csv_upload'),
# 	url(r'^api/sales_chart', 
# 		sales_chart, 
# 		name='sales_chart')
]

bible/models.py
from django.db import models
from django.urls import reverse

class Emotion(models.Model):
	name = models.CharField(max_length=50, unique=True)
	slug = models.SlugField(
		max_length=50,
		unique=True)

	def __str__(self):
		return self.name

	class Meta:
		ordering = ['name']

	def get_absolute_url(self):
		return reverse('emotion_list')

	def get_new_url(self):
		return reverse('verse_list', kwargs={'emotion': self.slug})

class Verse(models.Model):
	book = models.CharField(max_length=25)
	chapter = models.IntegerField()
	verses = models.CharField(max_length=10)
	text = models.TextField()
	slug = models.SlugField(max_length=25)
	
	emotion = models.ForeignKey(Emotion, on_delete=models.CASCADE)

	def __str__(self):
		return self.text

	class Meta:
		ordering = ['book']

	def get_absolute_url(self):
		return reverse('verse_detail', kwargs={'slug': self.slug})

	def get_update_url(self):
		return reverse('verse_update', kwargs={'slug': self.slug})

	def get_delete_url(self):
		return reverse('verse_delete', kwargs={'slug': self.slug})

bible/forms.py
from django import forms
from .models import Emotion, Verse
from django.core.exceptions import ValidationError

class EmotionForm(forms.ModelForm):
	class Meta:
		model = Emotion
		fields = '__all__'
		# this could also be "fields = ['name', 'slug']"

class VerseForm(forms.ModelForm):
	class Meta: 
		model = Verse
		fields = '__all__'

bible/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, CreateView, DetailView
import pdb

from .models import Emotion, Verse
from .forms import EmotionForm, VerseForm

# Create your views here.
class EmotionList(View):
	template_name = 'bible/emotion_list.html'

	def get(self, request):
		emotions = Emotion.objects.all()
		context = {'emotion_list':emotions}
		return render(request, self.template_name, context)

class EmotionCreate(CreateView):
	form_class = EmotionForm
	template_name = 'bible/emotion_create.html'

class VerseList(DetailView):
	template_name = 'bible/verse_list.html'
	emotion = ''

	def get(self, request, emotion):
		Verse.objects.values_list('emotion', flat=True)
		verses = Verse.objects.filter(emotion__slug=emotion)
		context = {'verse_list':verses}
		return render(request, self.template_name, context)

class VerseCreate(CreateView):
	form_class = VerseForm
	template_name = 'bible/verse_create.html'

class VerseDetail(DetailView):
	model = Verse

class VerseUpdate(View):
	form_class = VerseForm
	model = Verse
	template_name = 'bible/verse_update.html'

	def get(self, request, slug):
		verse = get_object_or_404(self.model, slug=slug)
		context = {
			'form':self.form_class(instance=verse),
			'verse':verse,}
		return render(request, self.template_name, context)

	def post(self, request, slug):
		verse = get_object_or_404(self.model, slug=slug)
		print(verse.slug)
		bound_form = self.form_class(request.POST, instance=verse)
		# if bound_form.is_valid():
		new_verse = bound_form.save()
		return redirect(new_verse)
#		else:
#			context = {
#				'form':bound_form,
#				'verse':verse,
#			}
#			return render(request, self.template_name, context)

class VerseDelete(View):
	def get(self, request, slug):
		verse = get_object_or_404(Verse, slug=slug)
		verse.delete()
		return render(request, 'bible/verse_confirm_delete.html', {'verse':verse})

# 	def post(self, request, slug):
# 		verse = get_object_or_404(Verse, slug=slug)
# 		verse.delete()
# 		return redirect('bible/emotion_list.html')

bible/templates/bible/emotion_create.html
{% extends parent_template|default:"base.html" %}

{% block title %}
{{ block.super }} - Create Emotion
{% endblock %}

{% block content %}
<div class="container">
	<div class="field">
		<form
			action="{% url 'emotion_create' %}"
			method="post">
			{% csrf_token %}
			{{ form.non_field_errors }}
			{{ form.name.errors }}
			<p>
				<label for="id_name" class="label">
					Name: 
				</label>
				{{ form.name }}
			</p>
			{{ form.slug.errors }}
			<p>
				<label for="id_slug" class="label">
					Slug: 
				</label>
				{{ form.slug }}
			</p>
			<p style="padding: 10px">
				<button type="submit" class="button is-primary">
					Create Emotion
				</button>
			</p>
		</form>
	</div>
</div>
{% endblock %}

bible/templates/bible/emotion_list.html
{% extends parent_template|default:"base.html" %}

{% block title %}
{{ block.super }} - Emotion List
{% endblock %}

{% block content %}
<div class="container">
	<div class="status row">
		{% if not emotion_list %}
			<div class="row">
				<p>
					You have no emotions...
				</p>
				<p>
					Please visit <a href="{% url 'emotion_create' %}">our create page </a> in order to add new emotions you robot. 
				</p>
			</div>
		{% else %}
			<p> 
				How are you feeling today?
			</p>
			<div class="row">
				{% for emotion in emotion_list %}
					<a href="{{ emotion.get_new_url }}" class="button is-primary is-large is-rounded">
						{{ emotion.name|title }}
					</a>
				{% endfor %}
			</div>
		{% endif %}
	</div>
</div>
{% endblock %}

bible/templates/bible/verse_confirm_delete.html
{% extends parent_template|default:"base.html" %}

{% block title %}
{{ block.super }} - Delete Verse
{% endblock %}

{% block content %}
	<p>Deleted</p>
{% endblock %}

bible/templates/bible/verse_create.html
{% extends parent_template|default:"base.html" %}

{% block title %}
{{ block.super }} - Create Emotion
{% endblock %}

{% block content %}
<div class="container">
	<div class="field">
		<form
			action="{% url 'verse_create' %}"
			method="post">
			{% csrf_token %}
			{{ form.non_field_errors }}
			{{ form.book.errors }}
			<p>
				<label for="id_book" class="label">
					Book: 
				</label>
				{{ form.book }}
			</p>
			{{ form.chapter.errors }}
			<p>
				<label for="id_chapter" class="label">
					Chapter: 
				</label>
				{{ form.chapter }}
			</p>
			{{ form.verses.errors }}
			<p>
				<label for="id_verses" class="label">
					Verses: 
				</label>
				{{ form.verses }}
			</p>
			{{ form.text.errors }}
			<p>
				<label for="id_text" class="label">
					Text: 
				</label>
				{{ form.text }}
			</p>
			{{ form.slug.errors }}
			<p>
				<label for="id_slug" class="label">
					Slug: 
				</label>
				{{ form.slug }}
			</p>
			{{ form.emotion.errors }}
			<p>
				<label for="id_emotion" class="label">
					Emotion: 
				</label>
				{{ form.emotion }}
			</p>
			<p style="padding: 10px">
				<button type="submit" class="button is-primary">
					Create Verse
				</button>
			</p>
		</form>
	</div>
</div>
{% endblock %}

bible/templates/bible/verse_detail.html
{% extends parent_template|default:"base.html" %}

{% block title %}
{{ block.super }} - Verse Detail
{% endblock %}

{% block content %}
<div class="container">
	<div class="status row">
		{{ verse.text|title }}
	</div>
</div>
{% endblock %}

bible/templates/bible/verse_list.html
{% extends parent_template|default:"base.html" %}

{% block title %}
{{ block.super }} - Verse List
{% endblock %}

{% block content %}
<div class="container">
	<div class="status row">
		{% if not verse_list %}
			<div class="row">
				<p>
					You have no verses for this emotion...
				</p>
				<p>
					Please visit <a href="{% url 'verse_create' %}">our create page </a> in order to add new verses. 
				</p>
			</div>
		{% else %}
			<p> 
				Hope these help.
			</p>
			{% for verse in verse_list %}
				<h3 class="subtitle is-3">{{ verse.book }} {{ verse.chapter }}.{{ verse.verses }}</h3>
				<div class="container" style="background-color: #ECECEC">
					<p style="padding: 10px">{{ verse.text }}</p>
				</div>
				<a href="{{ verse.get_absolute_url }}">Detail</a> | 
				<a href="{{ verse.get_update_url }}">Edit</a> | 
				<a href="{{ verse.get_delete_url }}">Delete</a>
				</br>
			{% endfor %}
		{% endif %}
	</div>
</div>
{% endblock %}

bible/templates/bible/verse_update.html
{% extends parent_template|default:"base.html" %}

{% block title %}
{{ block.super }} - Create Emotion
{% endblock %}

{% block content %}
<div class="container">
	<div class="field">
		<form
			action="{{ verse.get_update_url }}"
			method="post">
			{% csrf_token %}
			{{ form.non_field_errors }}
			{{ form.book.errors }}
			<p>
				<label for="id_book" class="label">
					Book: 
				</label>
				{{ form.book }}
			</p>
			{{ form.chapter.errors }}
			<p>
				<label for="id_chapter" class="label">
					Chapter: 
				</label>
				{{ form.chapter }}
			</p>
			{{ form.verses.errors }}
			<p>
				<label for="id_verses" class="label">
					Verses: 
				</label>
				{{ form.verses }}
			</p>
			{{ form.text.errors }}
			<p>
				<label for="id_text" class="label">
					Text: 
				</label>
				{{ form.text }}
			</p>
			{{ form.slug.errors }}
			<p>
				<label for="id_slug" class="label">
					Slug: 
				</label>
				{{ form.slug }}
			</p>
			{{ form.emotion.errors }}
			<p>
				<label for="id_emotion" class="label">
					Emotion: 
				</label>
				{{ form.emotion }}
			</p>
			<p style="padding: 10px">
				<button type="submit" class="button is-primary">
					Update Verse
				</button>
			</p>
		</form>
	</div>
</div>
{% endblock %}