arnold/urls.py
from django.contrib import admin
from django.urls import path, include
from bible import urls as bible_urls
from .views import homepage, aboutpage, youtubepage
from eoq import urls as eoq_urls
# from management import urls as management_urls
from lessons import urls as lessons_urls
from management import urls as management_urls
from fitness import urls as fitness_urls

urlpatterns = [
	path(r'', homepage, name='home_page'),
    path(r'admin/', admin.site.urls),
    path(r'about/', aboutpage, name='about_page'),
    path(r'bible/', include(bible_urls)),
    path(r'eoq/', include(eoq_urls)),
    path(r'youtube/', youtubepage, name='youtube_page'),
    # path(r'management/', management, include(management_urls)),
    path(r'lessons/', include(lessons_urls)),
    path(r'chart/', include(management_urls)),
    path(r'fitness/', include(fitness_urls)),
]

eoq/urls.py
from django.conf.urls import url
from .views import upload_file

urlpatterns = [
	url(r'^$',
		upload_file,
		name='csv_upload'),
# 	url(r'^api/sales_chart', 
# 		sales_chart, 
# 		name='sales_chart')
]

lessons/urls.py
from django.conf.urls import url
from .views import BookList, BookCreate, LessonCreate, LessonDetail, LessonList, LessonUpdate, LessonDelete, LessonReport
urlpatterns = [
	url(r'^$',
		BookList.as_view(),
		name='book_list'),
	url(r'^create/$',
		BookCreate.as_view(),
		name='book_create'),
	url(r'^lesson/create$',
		LessonCreate.as_view(),
		name='lesson_create'),
	url(r'^lesson/(?P<slug>[\w\-]+)/$',
		LessonDetail.as_view(),
		name='lesson_detail'),
 	url(r'^(?P<book>[\w\-]+)/$',
 		LessonList.as_view(),
 		name='lesson_list'),
 	url(r'^lesson/(?P<slug>[\w\-]+)/update/$',
 		LessonUpdate.as_view(),
 		name='lesson_update'),
 	url(r'^lesson/(?P<slug>[\w\-]+)/delete/$',
 		LessonDelete.as_view(),
 		name='lesson_delete'),
	url(r'^report',
		LessonReport.as_view(),
		name='lesson_report'),
]

bible/models.py
from django.db import models
from django.urls import reverse

class Emotion(models.Model):
	name = models.CharField(max_length=50, unique=True)
	slug = models.SlugField(
		max_length=50,
		unique=True)

	def __str__(self):
		return self.name

	class Meta:
		ordering = ['name']

	def get_absolute_url(self):
		return reverse('emotion_list')

	def get_new_url(self):
		return reverse('verse_list', kwargs={'emotion': self.slug})

class Verse(models.Model):
	book = models.CharField(max_length=25)
	chapter = models.IntegerField()
	verses = models.CharField(max_length=10)
	text = models.TextField()
	slug = models.SlugField(max_length=25)
	
	emotion = models.ForeignKey(Emotion, on_delete=models.CASCADE)

	def __str__(self):
		return self.text

	class Meta:
		ordering = ['book']

	def get_absolute_url(self):
		return reverse('verse_detail', kwargs={'slug': self.slug})

	def get_update_url(self):
		return reverse('verse_update', kwargs={'slug': self.slug})

	def get_delete_url(self):
		return reverse('verse_delete', kwargs={'slug': self.slug})

lessons/models.py
from django.db import models
from django.urls import reverse

BOOK_TOPICS = (
    ('leadership', 'leadership'),
    ('self improvement', 'self improvement'),
    ('technology', 'technology'),
    ('story', 'story'),
    ('fiction', 'fiction'),
    ('sales', 'sales'),
    ('management', 'management')
)

class Book(models.Model):
    book_name = models.CharField(max_length=50, unique=True)
    book_author = models.CharField(max_length=100)
    book_topic = models.CharField(max_length=50, choices=BOOK_TOPICS, default='leadership')
    slug = models.SlugField(max_length=50, unique=True)
    
    def __str__(self):
        return self.book_name
    
    class Meta:
        ordering = ['book_name']
    
    def get_absolute_url(self):
        return reverse('book_list')
    
    def get_new_url(self):
        return reverse('lesson_list', kwargs={'book': self.slug})

class Lesson(models.Model):
    lesson = models.TextField()
    slug = models.SlugField(max_length=25)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

    class Meta:
        ordering = ['lesson']

    def get_absolute_url(self):
    	return reverse('lesson_detail', kwargs={'slug': self.slug})

    def get_update_url(self):
    	return reverse('lesson_update', kwargs={'slug': self.slug})

    def get_delete_url(self):
    	return reverse('lesson_delete', kwargs={'slug': self.slug})

lessons/forms.py
from django import forms
from .models import Book, Lesson
from django.core.exceptions import ValidationError

class BookForm(forms.ModelForm):
	class Meta:
		model = Book
		fields = '__all__'
		# this could also be "fields = ['name', 'slug']"

class LessonForm(forms.ModelForm):
	class Meta: 
		model = Lesson
		fields = '__all__'

lessons/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, CreateView, DetailView
import pdb, psycopg2, re
import pandas as pa

from .models import Book, Lesson
from .forms import BookForm, LessonForm

# Create your views here.
class BookList(View):
	template_name = 'lessons/book_list.html'

	def get(self, request):
		books = Book.objects.all()
		context = {'book_list':books}
		return render(request, self.template_name, context)

class BookCreate(CreateView):
	form_class = BookForm
	template_name = 'lessons/book_create.html'

class LessonList(DetailView):
	template_name = 'lessons/lesson_list.html'
	book = ''

	def get(self, request, book):
		Lesson.objects.values_list('book', flat=True)
		lessons = Lesson.objects.filter(book__slug=book)
		context = {'lesson_list':lessons}
		return render(request, self.template_name, context)

class LessonCreate(CreateView):
	form_class = LessonForm
	template_name = 'lessons/lesson_create.html'

class LessonDetail(DetailView):
	model = Lesson

class LessonUpdate(View):
	form_class = LessonForm
	model = Lesson
	template_name = 'lessons/lesson_update.html'

	def get(self, request, slug):
		lesson = get_object_or_404(self.model, slug=slug)
		context = {
			'form':self.form_class(instance=lesson),
			'lesson':lesson,}
		return render(request, self.template_name, context)

	def post(self, request, slug):
		lesson = get_object_or_404(self.model, slug=slug)
		print(lesson.slug)
		bound_form = self.form_class(request.POST, instance=lesson)
		# if bound_form.is_valid():
		new_lesson = bound_form.save()
		return redirect(new_lesson)
#		else:
#			context = {
#				'form':bound_form,
#				'verse':verse,
#			}
#			return render(request, self.template_name, context)

class LessonDelete(View):
	def get(self, request, slug):
		lesson = get_object_or_404(Lesson, slug=slug)
		lesson.delete()
		return render(request, 'lessons/lesson_confirm_delete.html', {'lesson':lesson})

# 	def post(self, request, slug):
# 		verse = get_object_or_404(Verse, slug=slug)
# 		verse.delete()
# 		return redirect('bible/emotion_list.html')

# Time for everyone's favorite thing, reporting. 
class LessonReport(View):
	def get(self, request):
		table = pa.DataFrame(columns=['Lesson', 'Book Name', 'Book Topic'])
		conn = psycopg2.connect(host="localhost",database="arnold",user="postgres",password="snowlep")
		curs = conn.cursor()
		query = """
SELECT 
	l.lesson,
	b.book_name,
	b.book_topic
FROM lessons_lesson l
INNER JOIN lessons_book b
	ON l.book_id = b.id
ORDER BY book_name, lesson
	"""
		curs.execute(query)
		table.data = curs.fetchall()
		total = len(table.data)
		html_report(table)
		common = most_common_words(table)
		return render(request, 'lessons/lesson_report.html', context = {'testing':table.data, 'headers':table.columns, 'total':total, 'common_words':common})

# Generates the html for a stand alone report of my lessons learned. For learning purposes
def html_report(table):
	f = open('helloworld.html','w')
	webpage = """<html>\n<head></head>\n<body>\n<table style="border:1px solid black">\n<thead>\n"""
	for column in table.columns:
		webpage = webpage + """<th style="border:1px solid black">""" + column + "</th>\n"
	webpage = webpage + "</thead>\n"

	for row in table.data:
		webpage = webpage + """<tr>\n"""
		for dp in row:
			webpage = webpage + """<td style="border:1px solid black">""" + dp + "</td>\n"
		webpage = webpage + "</tr>"
	webpage = webpage + """</table>\n</body>\n</html>"""
	f.write(webpage)
	f.close()
	return table

# I want to get the word that most occures in my lesons, exluding commonly used words. 
def most_common_words(table):
	word_count = {}
	lessons = []
	bad_words = ['AND','THE', 'I', 'TO', 'A', 'IS', 'YOU', 'IN', 'OF', 'THAT', 
					'BE', 'ARE', 'YOUR', 'WITH', 'THINGS', 'ON', 'IT', '', 'FOR',
					'WHAT', 'SHOULD', 'AN', 'HAVE', 'CAN', 'WHEN', 'NOT', 'DO', 'AS',
					'OR', 'WILL', 'BY', 'IF', 'ONE', 'THIS', 'HOW', 'ABOUT', 'BUT',
					'FROM', 'AT', 'THAN', 'USE', 'THEY', 'THEIR', 'ALL', 'WHICH', 'THERE',
					'OTHER', 'THROUGH', 'LIKE', 'GET', 'WOULD', 'EACH', 'OUT']
	for data in table.data:
		lessons.append(data[0])
	for lesson in lessons:
		for word in lesson.split():
			word = re.sub('[^a-zA-Z]', '', word).upper()
			if word in word_count and word not in bad_words:
				word_count[word] += 1
			elif word not in bad_words:
				word_count[word] = 1
	if word_count.keys() in bad_words:
		print(word_count.keys())
		for word in bad_words:
			del word_count[word]
	sorted_word_count = {}
	for k in sorted(word_count, key=word_count.get, reverse=True):
		sorted_word_count[k] = word_count[k]
	ranking = 0
	top_words = []
	for word in list(sorted_word_count):
		top_words.append(word)
		ranking += 1
		if ranking == 15:
			break
	return top_words

lessons/templates/lessons/book_create.html
{% extends parent_template|default:"base.html" %}

{% block title %}
{{ block.super }} - Create Book
{% endblock %}

{% block content %}
<div class="container">
	<div class="field">
		<form
			action="{% url 'book_create' %}"
			method="post">
			{% csrf_token %}
			{{ form.non_field_errors }}
			{{ form.book_name.errors }}
			<p>
				<label for="id_name" class="label">
					Title: 
				</label>
				{{ form.book_name }}
			</p>
			{{ form.book_author.errors }}
			<p>
				<label for="id_name" class="label">
					Author: 
				</label>
				{{ form.book_author }}
			</p>
			{{ form.book_topic.errors }}
			<p>
				<label for="id_name" class="label">
					Topic: 
				</label>
				{{ form.book_topic }}
			</p>
			{{ form.slug.errors }}
			<p>
				<label for="id_slug" class="label">
					Slug: 
				</label>
				{{ form.slug }}
			</p>
			<p style="padding: 10px">
				<button type="submit" class="button is-primary">
					Create Book
				</button>
			</p>
		</form>
	</div>
</div>
{% endblock %}

lessons/templates/lessons/book_list.html
{% extends parent_template|default:"base.html" %}

{% block title %}
{{ block.super }} - Emotion List
{% endblock %}

{% block content %}
<div class="container">
	<div class="status row">
		{% if not book_list %}
			<div class="row">
				<p>
					It seems that you have not written any books, idiot...
				</p>
				<p>
					Please visit <a href="{% url 'book_create' %}">our create page </a> in order to add new books you idiot. 
				</p>
			</div>
		{% else %}
			<br>
			<a class="button is-primary" href="{% url 'book_create' %}">Add Book</a>
			</br>
			<div class="list is-hoverable">
				{% for book in book_list %}
					<a href="{{ book.get_new_url }}" class="list-item">
						{{ book.book_name|title }}
					</a>
				{% endfor %}
			</div>
		{% endif %}
	</div>
</div>
{% endblock %}

lessons/templates/lessons/lesson_confirm_delete.html
{% extends parent_template|default:"base.html" %}

{% block title %}
{{ block.super }} - Lesson Verse
{% endblock %}

{% block content %}
	<p>Deleted</p>
{% endblock %}

lessons/templates/lessons/lesson_create.html
{% extends parent_template|default:"base.html" %}

{% block title %}
{{ block.super }} - Create Lesson
{% endblock %}

{% block content %}
<div class="container">
	<div class="field">
		<form
			action="{% url 'lesson_create' %}"
			method="post">
			{% csrf_token %}
			{{ form.non_field_errors }}
			{{ form.lesson.errors }}
			<p>
				<label class="label">
					Lesson: 
				</label>
				{{ form.lesson }}
			</p>
			{{ form.slug.errors }}
			<p>
				<label id="mySlug" for="id_slug" class="label">
					Slug: 
				</label>
				{{ form.slug }}
			</p>
			{{ form.book.errors }}
			<p>
				<label for="id_book" class="label">
					Book: 
				</label>
				{{ form.book }}
			</p>
			<p style="padding: 10px">
				<button type="submit" class="button is-primary">
					Create Lesson
				</button>
			</p>
		</form>
	</div>
</div>

{% endblock %}


lessons/templates/lessons/lesson_detail.html
{% extends parent_template|default:"base.html" %}

{% block title %}
{{ block.super }} - Lesson Detail
{% endblock %}

{% block content %}
<div class="container">
	<p>
		<a href="{% url 'book_list' %}">Return to Book List</a>
	</p>
	<div class="status row">
		{{ lesson.lesson|title }}
	</div>
</div>
{% endblock %}

lessons/templates/lessons/lesson_list.html
{% extends parent_template|default:"base.html" %}

{% block title %}
{{ block.super }} - Lesson List
{% endblock %}

{% block content %}
<div class="container">
	<div class="status row">
		{% if not lesson_list %}
			<div class="row">
				<p>
					You have no lessons for this book...
				</p>
				<p>
					Please visit <a href="{% url 'lesson_create' %}">our create page </a> in order to add new verses. 
				</p>
			</div>
		{% else %}
			<a href="{% url 'lesson_create' %}" class="button is-primary">Add Lesson</a>
			<p> 
				Hopefully you can learn something from these.
			</p>
			</br>
			{% for lesson in lesson_list %}
				<div class="list is-hoverable">
					<div class="list-item">
						<p>{{ lesson.lesson }}</p>
						<a href="{{ lesson.get_absolute_url }}">Detail</a> | 
						<a href="{{ lesson.get_update_url }}">Edit</a> | 
						<a href="{{ lesson.get_delete_url }}">Delete</a>
					</div>
				</div>
			</br>
			{% endfor %}
		{% endif %}
		<div class="status row">
			<a class="button is-primary" href="{% url 'book_list' %}">Return to book list</a>
		</div>
	</br>
	</div>
</div>
{% endblock %}

lessons/templates/lessons/lesson_report.html
{% extends parent_template|default:"base.html" %}

{% block title %}
{{ block.super }} - Lessons Report
{% endblock %}

{% block content %}
<div class="container">
    <table class="table is-striped">
        <thead>
            {% for header in headers %}
            <th>{{ header }}</th>
            {% endfor %}
        </thead>
    {% for test in testing %}
    <tr>
        {% for item in test %}
            <td>{{ item }}</td>
        {% endfor %}
    </tr>
    {% endfor %}
    </table>
    <p>
        Total number of lessons learned {{ total }}
    </p>
    <h3>
        Top words that I have been using:
    </h3>
    <div class="container">
    <ol style="padding-left: 50px;">
        {% for word in common_words %}
        <li>
            {{ word }}
        </li>
        {% endfor %}
    </ol>
    </div>
</div>
{% endblock %}

lessons/templates/lessons/lesson_update.html
{% extends parent_template|default:"base.html" %}

{% block title %}
{{ block.super }} - Create Emotion
{% endblock %}

{% block content %}
<div class="container">
	<div class="field">
		<form
			action="{{ lesson.get_update_url }}"
			method="post">
			{% csrf_token %}
			{{ form.non_field_errors }}
			{{ form.lesson.errors }}
			<p>
				<label for="id_lesson" class="label">
					Lesson: 
				</label>
				{{ form.lesson }}
			</p>
			{{ form.slug.errors }}
			<p>
				<label for="id_slug" class="label">
					Slug: 
				</label>
				{{ form.slug }}
			</p>
			{{ form.book.errors }}
			<p>
				<label for="id_book" class="label">
					Book: 
				</label>
				{{ form.book }}
			</p>
			<p style="padding: 10px">
				<button type="submit" class="button is-primary">
					Update Lesson
				</button>
			</p>
		</form>
	</div>
</div>
{% endblock %}